"""new fields in user model

Revision ID: 243c81373309
Revises: dc2a8f75a073
Create Date: 2023-01-12 21:27:07.724707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '243c81373309'
down_revision = 'dc2a8f75a073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
